language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

script:
  - ./gradlew clean assembleDebug testDebugUnitTestCoverage coveralls

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
